dbConfig:
  driverName: mysql
  dsn: root:Gcx199815.@tcp(127.0.0.1:3306)/niuNiuSDK?charset=utf8mb4&parseTime=true&loc=Local
  showSql: true
  showExecTime: false
  maxIdle: 10
  maxOpen: 200
log:
  path: ./run/niuNiuWhiteBoard
  level: debug
redisConfig:
  name: redis
  type: tcp
  address: 127.0.0.1:6379
  auth:



